##
# This file is used by aws clouddeploy to know how to update the ee nodes
##
version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: /.codedeploy/before_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /.codedeploy/stop_server.sh
      timeout: 300
      runas: root
