#!/bin/bash
# Set environment variables for scripts so that they point to https://github.com/streamr-dev/streamr-docker-dev/
# This is the testing environment
# Source this file to use: `source setup_dev`

export ETHEREUM_SERVER=http://localhost:8545
export STREAMR_NODE_ADDRESS=0xFCAd0B19bB29D4674531d6f115237E16AfCE377c
export STREAMR_WS_URL=ws://localhost:8890/api/v1/ws
export STREAMR_HTTP_URL=http://localhost:8081/streamr-core/api/v1

export TOKEN_ADDRESS=0xbAA81A0179015bE47Ad439566374F2Bae098686F
export DATAUNION_ADDRESS=  # TODO: find out, or maybe add a data union into the parity init?

# start_server
export WEBSERVER_PORT=8085
export OPERATOR_PRIVATE_KEY=0x5e98cce00cff5dea6b454889f359a4ec06b9fa6b88e9d69b86de8e1c81887da0 # ganache 0

# deploy
export BLOCK_FREEZE_SECONDS=1
export OPERATOR_ADDRESS=0xa3d1F77ACfF0060F7213D7BF3c7fEC78df847De1      # ganache 0
export ADMIN_FEE=0.3
export GAS_PRICE_GWEI=20

# add_secret, join_dataunion
export SECRET=secret

# send_tokens
export DATA_TOKEN_AMOUNT=0.01

# useful test accounts:
export ETHEREUM_PRIVATE_KEY=5E98CCE00CFF5DEA6B454889F359A4EC06B9FA6B88E9D69B86DE8E1C81887DA0 # ganache 1
#export ETHEREUM_PRIVATE_KEY=4059de411f15511a85ce332e7a428f36492ab4e87c7830099dadbf130f1896ae # ganache 3
#export ETHEREUM_PRIVATE_KEY=1000000000000000000000000000000000000000000000000000000000000000
#export ETHEREUM_PRIVATE_KEY=1000000000000000000000000000000000000000000000000000000000000001 # etc. up to ...999

report_ok () {
    echo ${1:-monitor} OK
}

report_fail () {
    echo *** ${1:-monitor} FAIL ***
}

assert_exit_code_zero () {
    if [ $? -eq 0 ]
    then
        echo OK $1
    else
        echo FAIL $1: exit code $?
        exit $?
    fi
}
