#!/bin/bash

#export DEBUG=StreamrClient*

# docker env
export ETHEREUM_SERVER=http://localhost:8545
export STREAMR_NODE_ADDRESS=0xFCAd0B19bB29D4674531d6f115237E16AfCE377c
export STREAMR_WS_URL=ws://localhost/api/v1/ws
export STREAMR_HTTP_URL=http://localhost/api/v1

# start_server.js without env variables
#export ETHEREUM_SERVER=http://localhost:8548
#export STREAMR_NODE_ADDRESS=0xc0aa4dC0763550161a6B59fa430361b5a26df28C
export COMMUNITY_ADDRESS=0x5159fbf2e0ff63e35b17293416fdf7a0909a0cda
export WEBSERVER_PORT=8085

# both dev envs
export TOKEN_ADDRESS=0xbAA81A0179015bE47Ad439566374F2Bae098686F
export ETHEREUM_PRIVATE_KEY=0x5e98cce00cff5dea6b454889f359a4ec06b9fa6b88e9d69b86de8e1c81887da0 # ganache 0
#export ETHEREUM_PRIVATE_KEY=4059de411f15511a85ce332e7a428f36492ab4e87c7830099dadbf130f1896ae # ganache 3

# add_secret, join_community
export SECRET=6pKbPk2aQ0i7qLcVcEpzEwOdJDjEH8TF2aE-67HdTEAw
export JOINS_PER_MINUTE_AVERAGE=0.1
export REVENUE_PER_MINUTE=1
export REVENUE_PER_TRANSFER=0.2

node scripts/fake_activity.js
#node scripts/start_server.js
#node scripts/deploy_community.js
#node scripts/add_secret.js
#node scripts/join_community.js
#node scripts/check_community.js
#node scripts/send_tokens.js
