#!/bin/bash

# Uncomment to enable StreamrClient logging
#export DEBUG=StreamrClient*

# Setup environment
export ETHEREUM_SERVER=http://localhost:8545
export STREAMR_WS_URL=ws://localhost/api/v1/ws
export STREAMR_HTTP_URL=http://localhost/api/v1
export TOKEN_ADDRESS=0xbAA81A0179015bE47Ad439566374F2Bae098686F
export MARKETPLACE_ADDRESS=0xF1371c0f40528406dc4f4cAf89924eA9Da49E866
export BUYER_WALLET_PRIVATE_KEY=0x5e98cce00cff5dea6b454889f359a4ec06b9fa6b88e9d69b86de8e1c81887da0 # ganache 0
#export ETHEREUM_SERVER=https://staging.streamr.com:8540
#export STREAMR_WS_URL=wss://staging.streamr.com/api/v1/ws
#export STREAMR_HTTP_URL=https://staging.streamr.com/api/v1
#export TOKEN_ADDRESS=0x67a9fda28c4df570d1d5350acfa345194f4d4100
#export MARKETPLACE_ADDRESS=0x98af5996A5cbfAC95aE1E860cBD60d472f214Be0
#export BUYER_WALLET_PRIVATE_KEY=0x3e4327981b9ebc3b7df2af23f1a55be0c2e04ee5d88c58402dfd30c880313f45 # staging acc 3

# Set generator parameters
export COMMUNITY_ADDRESS=0xBE99E9f0836a71CA91cbfAC6EDCc2146d7857013
export SECRET=suohklggQ3u8EyU02x1U1QnJ2dUiomRbi9ip7ueXZDwg
export JOINS_PER_MINUTE_AVERAGE=1
export PURCHASES_PER_MINUTE=0.5
export PURCHASE_SUBSCRIPTION_LENGTH_SECS_MIN=3600
export PURCHASE_SUBSCRIPTION_LENGTH_SECS_MAX=18000

node scripts/fake_activity.js
